# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets :
        recipe_image :
            quality: 75
            filters :
                fixed:
                    width: 1350
                    height: 650
        user_avatar :
            quality: 75
            filters :
                thumbnail:
                    size: [300, 300]
                    mode: outbound

